# 关于Config.yml配置文件解析详情请见 https://www.yuque.com/ctimet/specialbektwiki/az3bgr
options:
  check-update: true
  auto-register: false

timer:
  delay: 10
  period: 10

mysql:
  enabled: false
  host: localhost
  port:
  user:
  password:
  database: